Minor fix to correctly filter Cassandra nodes from bastion host
datastax/diagnostic-collection pull request #120
Opened 2022-04-14 17:47 UTC by joelsdc

Currently when a running the discovery phase the script checks for Cassandra nodes and exits if detects a match:
https://github.com/datastax/diagnostic-collection/blob/744e043562abfc145aa2e9fb4642209e2778c8c0/ds-collector/ds-collector#L147-L151

Say, for example, you have a 15 Cassandra node cluster, with IPs:
```
192.168.0.1/24
...
192.168.0.15/24
```

And your bastion host has the IP `192.168.0.100`

When running the above check, the bastion IP of `192.168.0.100` would be a match with Cassandra node `192.168.0.10` and thus the script errors out.

This patch fixes that.

2022-04-15 13:37 UTC, michaelsembwever commented on ds-collector/ds-collector
> +      ${ip_command} | grep -q '${ip}/' && { echo >&2 "The ds-collector script cannot be executed from a Cassandra/DSE node. Please execute the script from a jumpbox/bastion server that has access to
this won't work when using `ipconfig`.

i'm guessing we need something like…
```suggestion
      ${ip_command} | grep -q '${ip}[/ ]' && { echo >&2 "The ds-collector script cannot be executed from a Cassandra/DSE node. Please execute the script from a jumpbox/bastion server that has access to all nodes to the data-center/cluster."; exit 1; }
```

2022-04-15 13:38 UTC, michaelsembwever requested changes
changes required to get it to work when using `ifconfig`

2022-04-19 17:29 UTC, joelsdc commented
Added!

2022-04-19 18:21 UTC, michaelsembwever approved these changes
👍

2022-04-19 18:21 UTC, michaelsembwever commented
@mieslep do you wanna eyeball this too?

2022-04-22 10:49 UTC, merged